### ISSUE TITLE
Crash (and not working) on multiplayer mode

### ISSUE THREAD

**Issue by UMRnInside** [AlexHalogen/VillageInfo#1]
Crash report(Gist): https://gist.github.com/UMRnInside/9ccac08fb5132bfd70e62ebe8164a83d
Minecraft crashes when connected to a server and press F3.

**Comment by AlexHalogen** [comment]
Hi!
Sorry for the late reply. This mod is for singleplayer and lan hosts only.
I pushed a fix so that the game won't crash in multiplayer mods.
Hope this helps.

**Comment by UMRnInside** [comment]
Roger that.
